parameters:
    biz_config:
        debug: "%kernel.debug%"
        db.options: "%biz_db_options%"
        root_directory: "%kernel.root_dir%/../"
        cache_directory: "%kernel.cache_dir%"
        log_directory: "%kernel.logs_dir%"
        kernel.root_dir: "%kernel.root_dir%"
        upload.public_directory: "%upload.public_directory%"
        upload.public_url_path: "%upload.public_url_path%"
        upload.private_directory: "%upload.private_directory%"

    biz_db_options:
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        host: "%database_host%"
        port: "%database_port%"
        driver: pdo_mysql
        charset: UTF8

services:
    biz:
        class: Codeages\Biz\Framework\Context\Biz
        arguments: ["%biz_config%"]
