imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: biz.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.csrf.token_id.default: app
    app.csrf.token_form_name: _csrf_token
    upload.public_directory: "%kernel.root_dir%/../web/files"
    upload.public_url_path: "/files"
    upload.private_directory: "%kernel.root_dir%/../var/data/private_files"

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"], logging: false }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        name: SID
        gc_maxlifetime: 7200
    fragments:       ~
    http_method_override: true
    assets:
        version: '1.0.0'


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        default_csrf_token_id: "%app.csrf.token_id.default%"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

sentry:
    dsn: "%sentry_dsn%"