imports:
    - { resource: event_subscribers.yml }

services:
    biz.service_provider.collector:
        class: Biz\ServiceProviderCollector
        
    biz.event_subscriber.collector:
        class: Biz\EventSubscriberCollector
      
    extension.manager:
        class: AppBundle\Extension\ExtensionManager
        
    app.twig_extension.html:
        class: AppBundle\Twig\HtmlExtension
        arguments: ['@service_container']
        public: false
        tags:
            - { name: twig.extension }
    
    app.twig_extension.permission:
        class: AppBundle\Twig\PermissionExtension
        arguments: ['@service_container']
        public: false
        tags:
            - { name: twig.extension }
            
    app.twig_extension.data:
        class: AppBundle\Twig\DataExtension
        arguments: ['@service_container']
        public: false
        tags:
            - { name: twig.extension }
            
    app.twig_extension.dict:
        class: AppBundle\Twig\DictExtension
        arguments: ['@service_container']
        public: false
        tags:
            - { name: twig.extension }
    
    app.listener.exception_listener:
        class: AppBundle\Listener\ExceptionListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority:255 }
            
    app.csrf_token_validate_listener:
        class: AppBundle\Listener\CsrfTokenValidateListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority:255 }
    
    app.user.login_handler:
        class: AppBundle\Handler\LoginSuccessHandler
        arguments: ['@service_container', '@security.authorization_checker']
        tags: [{ name: kernel.event_listener, event: security.interactive_login, priority:255}]
    
    app.controller.permission_listener:
        class: AppBundle\Listener\PermissionListener
        arguments:    ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority:255 }
    
    biz.permission_builder:
        class: Biz\Permission\PermissionBuilder
        arguments: ['@biz']
        
    app.extension.data_tag:
        class: AppBundle\Extension\DataTagExtension
        calls:
            - [setBiz, ['@biz']]
        tags:
            - { name: extension }

    